#!/bin/sh
# Part of spindle http://asbradbury.org/projects/spindle
#
# See LICENSE file for copyright and license details

set -ex

. ./common

CURIMG=stage4-lxde.$IMGFORMAT

upgrade_jessie() {
  # we may want to break out DEBIAN_FRONTEND=noninteractive
  ssh_in_to_qemu chroot /mnt sh -l -ex - <<EOF
sed -i "s|wheezy|jessie|g" /etc/apt/sources.list
apt-get update
DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true LC_ALL=C LANGUAGE=C LANG=C aptitude install -y xorg fluxbox fbsetbg fbrun
DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true LC_ALL=C LANGUAGE=C LANG=C aptitude install -y xdg-utils
DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true LC_ALL=C LANGUAGE=C LANG=C aptitude install -y git-core rpi-update
DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true LC_ALL=C LANGUAGE=C LANG=C aptitude install -y dist-upgrade
DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true LC_ALL=C LANGUAGE=C LANG=C aptitude install -y upgrade

EOF
}


install_wayland() {
  onvm_chroot sh -l -ex - <<\EOF
DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true LC_ALL=C LANGUAGE=C LANG=C aptitude install weston
}



configure_primark() {
  onvm_chroot sh -l -e <<\EOF
## get the background from are server packages.  
#DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true LC_ALL=C LANGUAGE=C LANG=C 
cd /tmp

wget http://primark.netgear.com/debian/archive/jessie/primark-background-0.1.armhf.deb
wget http://primark.netgear.com/debian/archive/jessie/primark-icons-0.1.armhf.deb

# change background

update-alternatives --install /usr/share/images/desktop-base/desktop-background \
  desktop-background /usr/share/background/primark/background.jpg 100
PCMANFMCFG=/etc/xdg/pcmanfm/LXDE/pcmanfm.conf
EOF
}

setup_automounting() {
  onvm_chroot sh -l -e <<\EOF1
apt-get install -y udisks
cat <<EOF2 > /etc/polkit-1/localauthority/50-local.d/55-storage.pkla
[Storage Permissions]
Identity=unix-group:plugdev
Action=org.freedesktop.udisks.filesystem-mount;org.freedesktop.udisks.drive-eject;org.freedesktop.udisks.drive-detach;org.freedesktop.udisks.luks-unlock;org.freedesktop.udisks.inhibit-polling;org.freedesktop.udisks.drive-set-spindown
ResultAny=yes
ResultActive=yes
ResultInactive=no
EOF2
EOF1
}

install_qt4(){
  onvm_chroot sh -l -e <<\EOF

DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true LC_ALL=C LANGUAGE=C LANG=C aptitude install -y qt4-default qt4-qmlviewer

DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true LC_ALL=C LANGUAGE=C LANG=C aptitude install -y libqt4-sql-sqlite libbotan-1.10-0 libc6 libgcc1 libqt4-declarative  libqt4-network libqt4-script

DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true LC_ALL=C LANGUAGE=C LANG=C aptitude install -y libqt4-sql libqt4-svg libqt4-xml libqtcore4 libqtgui4 libqtwebkit4

DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true LC_ALL=C LANGUAGE=C LANG=C aptitude install -y libstdc++6 gdb make qt4-dev-tools xterm

DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true LC_ALL=C LANGUAGE=C LANG=C aptitude install -y libgl1-mesa-dev libglu1-mesa-dev libqt4-dev libqt4-opengl libgl1-mesa-glx 


EOF
}

install_qt5() {
  onvm_chroot sh -l -e <<\EOF
DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true LC_ALL=C LANGUAGE=C LANG=C aptitude install -y qt5-default qmlscene libqt5qml5 libqt5quick5 libqt5quickparticles5
EOF
}

cd $WORKDIR
dotask branch_image ../$OUTDIR/stage3.$IMGFORMAT $CURIMG
dotask run_qemu $CURIMG
dotask mount_apt_cache
dotask disable_starting_services
dotask upgrade_jessie
dotask install_qt4
#dotask install_qt5
#dotask install_wayland
dotask setup_automounting
dotask save_space_using_hardlink
dotask allow_starting_services
dotask update_issue
dotask fingerprint_debian
dotask shutdown_qemu
dotask finish_image
